# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b93af93d4621885de19b32f09c108ebc3c4fef0eeb032308e15cb24c0a9fc2ad25e1139c1424edaa56b2c1b84f296c16c923181f4459906059bfdcffa705288

test:
  secret_key_base: d84f92a21483b1c5a50e1f2bedb75d7e2abf682e45f95b2140c60830614171f65c84631c85451519b302b7e3a4b59c7fc2eb43fec040b6a2aa4a5973a41408e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
